### ISSUE TITLE
in android doesn't play after it finishes

### ISSUE THREAD

**Issue by mluria** [nchutchind/cordova-plugin-streaming-media#10]
I fixed this by commenting out:

stop()

inOncomplete

Is this the desired functionality?

**Comment by jonlil** [comment]
@mluria did you get the shouldAutoClose option to work? On android 5.x for me it doesn't work :(

**Comment by sparkrevolutions** [comment]
Looking through SimpleVideoStream.java inside the plugin, it is implemented under the property `shouldAutoClose`. Default is true.

**Comment by gitlovenotwar** [comment]
I have the same problem. After the video plays, it doesn't play anymore. Also, neither the forward/backward button works.

**Comment by shamilovtim** [comment]
Should be resolved with latest
