### ISSUE TITLE
Only Full Screen?

### ISSUE THREAD

**Issue by naguchennai** [nchutchind/cordova-plugin-streaming-media#103]
How can i add Player view? and player control (half screen like youtube app)
how can i play video in half screen?
how can i add full screen video button? onclick full screen?

So finally it only work full screen?

**Comment by shamilovtim** [comment]
@naguchennai use inline html5 video and native javascript controls (e.g. play(), etc.)

issue can be closed

**Comment by shamilovtim** [comment]
if there's a clear reason for needing this in this plugin i'll reopen but this is easily resolved by using html5 inline video. this is a fullscreen video plugin.

**Comment by ghost** [comment]
Html video with autoplay does not work in ios low power mode
