### ISSUE TITLE
top buttons, including done and close are hard to access/hidden on iPhoneX

### ISSUE THREAD

**Issue by KevRyan2** [nchutchind/cordova-plugin-streaming-media#108]
Using v3.14.0 of this plugin on ionic 3.16.0, iOS 11.1, iPhoneX.

When a video is launched to full screen with this plugin, the "Done" button as well as the close button are both nested underneath the time and the signal/battery level status bar indicators.  Need a fix asap for iPhone X which provides an option/parameter that will push only the buttons down 20-30px (while keeping the video at fullscreen to still make use of the entire iPhoneX screen).

http://prntscr.com/h67r4y

**Comment by shamilovtim** [comment]
merged
