### ISSUE TITLE
AirPlay support

### ISSUE THREAD

**Issue by wildMag** [nchutchind/cordova-plugin-streaming-media#11]
Hi is there a way to enable airplay support with this plugin ? 
When I select the airplay icon in the bottom right corner on the device and try to enable streaming to the TV, a loading icon appears on TV but the video is not being played.

thanks

**Comment by shamilovtim** [comment]
Resolved with latest

**Comment by Topiya** [comment]
Can you please let me know that How to Enable/Integrate AirPlay using this plugin in Ionic app?
