### ISSUE TITLE
No audio iOS 11

### ISSUE THREAD

**Issue by johnbran** [nchutchind/cordova-plugin-streaming-media#110]
**What version of Streaming-Meda-Cordova-Plugin are you using? 0.1.4

**What version of Cordova are you using?** 7.1.0

**What devices are affected?** iOS 11

**Please describe the issue in detail, with relevant code samples**
url = "https://goabits.com/dijiTribe/php/temp/mp3.mp3";
options = {
                    bgColor: "#FFFFFF",
                    bgImage: "https://goabits.com/dijiTribe/img/audio.png",
                    bgImageScale: "fit", // other valid values: "stretch"
                    initFullscreen: true, // true(default)/false iOS only
                  
                };

window.plugins.streamingMedia.playAudio(url,options);

No audio is played in both mp3 files and video files (mov & m4v tested) 

**What did you expect to happen?** audio to play

**What actually happened?** video with no audio when playing video files. No audio with audio only files.

**Comment by tombpain** [comment]
Did you find a solution to this problem?

**Comment by crlang44** [comment]
Second that, any luck on finding a solution?

**Comment by tombpain** [comment]
I switched back to videogular as the audio from the stream is piped through the audio channel that is affected by the mute slider on the device. My client said the app was broken as his slider was switched to mute and as this is not the general behaviour of native app. Didn't seem to be any way to switch to the correct channel... :(

**Comment by jonasmedeiros** [comment]
Only way to fix is use Audio Object from Javascript

**Comment by shamilovtim** [comment]
To resolve, encode your video *.aac audio. Current version will not player mp3 layer 1/2.

**Comment by shamilovtim** [comment]
please confirm this wasn't fixed after new PRs were merged

**Comment by shamilovtim** [comment]
The latest version should have resolved this. Please use *.aac audio embedded in videos.
