### ISSUE TITLE
How to use bgImage ?

### ISSUE THREAD

**Issue by kamiloc** [nchutchind/cordova-plugin-streaming-media#113]
I'm using the next code:

`playAudio(audioUrl: string) {
    this.streamingMedia.playAudio(
      '/path/to/audio/file',
      { initFullscreen: false, bgColor: 'white', bgImage: 'assets/imgs/volume.png', bgImageScale: 'fit'});
  }`

and the bgImage property doesn't work.

Can you explain how to use it ?

**Comment by mubasshir** [comment]
did you find solution to this?

**Comment by kamiloc** [comment]
Not yet, i'm waiting  a response for the repo owner ...

**Comment by mubasshir** [comment]
I tried full http path eg. https://d30y9cdsu7xlg0.cloudfront.net/png/11299-200.png
This worked for me, although gif did not work

**Comment by GreyHat147** [comment]
The Url http works for me, as well.
