### ISSUE TITLE
orientation option not working on ios.

### ISSUE THREAD

**Issue by ugurozcan** [nchutchind/cordova-plugin-streaming-media#114]
**What version of Streaming-Meda-Cordova-Plugin are you using?**
4.5.2
**What version of Cordova are you using?**
7.1.0
**What devices are affected?**
ios all device
**Please describe the issue in detail, with relevant code samples**
let options: StreamingVideoOptions = {
        successCallback: () => { 
        },
        errorCallback: (e) => { 
        },
        orientation: 'landscape'
      };
      this.streamingMedia.playVideo(url_str.toString(), options);
**What did you expect to happen?**

**What actually happened?**

**Comment by ttibau** [comment]
+1

**Comment by shamilovtim** [comment]
See #132 for force landscape on iOS. This uses the new AVPlayerViewController PR. If you want to do something different you will need to alter the iOS code directly.

**Comment by shamilovtim** [comment]
#132 resolves this. not yet available on NPM, reference the repo directly for now.
