### ISSUE TITLE
Local video - MediaPlayer Error: Unknown (1) -2147483648

### ISSUE THREAD

**Issue by matodrobec** [nchutchind/cordova-plugin-streaming-media#115]
The plugin is not playing local files on android. I am gettting error `MediaPlayer Error: Unknown (1) -2147483648`. The file path is `file:///android_asset/www/assets/media/video.mp4` .  It is working with com.moust.cordova.videoplayer 1.0.1 "Video Player" but I would like to use this cordova plugin streaming media.

info :
* android:  4.4.2
* com.hutchind.cordova.plugins.streamingmedia 0.1.4 "StreamingMedia"
* cordova (Cordova CLI) : 8.0.0
* Cordova Platforms  : android 7.0.0
* Ionic Framework    : ionic-angular 3.9.2
* Android SDK Tools : 25.2.5

Thanks you for help.

**Comment by Topiya** [comment]
@matodrobec 
Did you find any solution so far regarding this?

**Comment by Topiya** [comment]
@matodrobec 
Have you got any solution so far?

**Comment by shamilovtim** [comment]
@Topiya I am able to play local files just fine stored on the actual android file system. try getting the reath path of the file with the file api

**Comment by shamilovtim** [comment]
proposed enhancement: handle local file:/// path elegantly and normalize the URL for users
