### ISSUE TITLE
Error Android

### ISSUE THREAD

**Issue by khalisafkari** [nchutchind/cordova-plugin-streaming-media#118]
the video closes itself after 30 seconds before the video runs out

**Comment by ajayrcdev** [comment]
same with me and https://github.com/nchutchind/cordova-plugin-streaming-media/issues/105

**Comment by shamilovtim** [comment]
which devices? can you host the source video on the web and provide a link to it?

**Comment by AcidTr** [comment]
I'm trying to play a video and the video player open and close right after.
Source video:
'https://vimeo.com/86064716'

**Comment by shamilovtim** [comment]
Vimeo is a social media site, not video storage. That's why the following link "https://vimeo.com/86064716" takes you to an HTML webpage, not a video. If you want to stream video you need to link to the **actual video file**. Not an HTML webpage. I'm not sure how that works on vimeo

**Comment by AcidTr** [comment]
I got it right now. I just noticed that some videos have a download link that works fine.
