### ISSUE TITLE
Error! MEdia Player Error Unknown(1) -2147483648

### ISSUE THREAD

**Issue by kapilkarda** [nchutchind/cordova-plugin-streaming-media#12]
I am using this but it give error please help me.

**Comment by duyongxin** [comment]
got same error ,please help!

Error! Media Player Error: Unknown (1) -2147483648

wav file stream

**Comment by blukee** [comment]
Only see this error on HTC Desire x.

**Comment by faceleg** [comment]
Closing, reopen if still an issue.

**Comment by aamir1995** [comment]
still an error, please reopen

**Comment by jinnyjo** [comment]
I am facing the same issue.
