### ISSUE TITLE
Support for image change while playing

### ISSUE THREAD

**Issue by manprit-sahota** [nchutchind/cordova-plugin-streaming-media#124]
**What version of Streaming-Media-Cordova-Plugin are you using?**
3.0.9

**What version of Cordova are you using?**

**What devices are affected?**
Android

**Please describe the issue in detail, with relevant code samples**

**What did you expect to happen?**
I want to change the image of audio track while it is already playing? Is it possible or I need any trick for the same?

**What actually happened?**

**Comment by shamilovtim** [comment]
i don't see this being on the roadmap. you're welcome to contribute a PR.
