### ISSUE TITLE
audio play back stopped in android screen lock

### ISSUE THREAD

**Issue by oghanbari** [nchutchind/cordova-plugin-streaming-media#125]
hi, thanks for your good product
i have tried cordova streaming media plugin for playing audio in my android project but i have problem when i am playing audio using PlayAudio function in android 5 when screen get locked audio playback stopped but when i play music with PlayVideo function it's play completely without interrupt but screen is blacken and i do not like it, how can i use PlayAudio like PlayVideo but keep screen awake?

**Comment by shamilovtim** [comment]
@oghanbari the audio will now play even if the screen is off. you now have the option of keeping the screen turned on with `keepAwake` as well if you want the screen not to shut off.
