### ISSUE TITLE
Hidden Player (Underground play)

### ISSUE THREAD

**Issue by acefxlabs** [nchutchind/cordova-plugin-streaming-media#126]
Hello,
How can i make the native player hidden and just play underground. 
I have forked this repo and made several changes to the java files but since i am not really a java guy it did not work. 

Please i urgently need this as it is the only player i have been able to use to get my stream to play without delay on android

Thanks

**Comment by shamilovtim** [comment]
@acefxlabs you're looking for sound to play while the app is minimized?

**Comment by shamilovtim** [comment]
Resolved with 2.0
