### ISSUE TITLE
Error -19 when running on Android

### ISSUE THREAD

**Issue by mdc555** [nchutchind/cordova-plugin-streaming-media#129]
Just trying this plugin to play an audio streaming but always getting Error -19 and I can't find info about this error.

**What version of Streaming-Meda-Cordova-Plugin are you using?**
    "cordova-plugin-streaming-media": "^1.0.2",
**What version of Cordova are you using?**
   "cordova-android": "~7.0.0"
**What devices are affected?**
Android
**Please describe the issue in detail, with relevant code samples**
Just trying to play an audio streaming and getting Error -19
**What did you expect to happen?**
Be able to play the audio
**What actually happened?**
Nothing... Just the error

**Comment by shamilovtim** [comment]
Try using the latest version from npm
