### ISSUE TITLE
bgImage not working with AVPlayerViewController

### ISSUE THREAD

**Issue by shkbahmad** [nchutchind/cordova-plugin-streaming-media#137]
**What version of Streaming-Meda-Cordova-Plugin are you using?**
2.0.0

**What version of Cordova are you using?**
7.1.0

**What devices are affected?**
iOS

**Please describe the issue in detail, with relevant code samples**
bgImage and bgColor do not work with the new AVPlayerViewController.
```
var options = {
    bgColor: "#FFFFFF",
    bgImage: "https://123.example.com/png/11299-200.png",
    bgImageScale: "fit", // other valid values: "stretch"
    initFullscreen: false, // true(default)/false iOS only
    successCallback: function() {
      console.log("Player closed without error.");
    },
    errorCallback: function(errMsg) {
      console.log("Error! " + errMsg);
    }
  };
  window.plugins.streamingMedia.playAudio(audioUrl, options);
```

**What did you expect to happen?**
For the background image to be displayed.

**Comment by shamilovtim** [comment]
Resolved with 2.1
