### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by moeidsaleem** [nchutchind/cordova-plugin-streaming-media#139]
While building .apk its not working, I have tried removing and reinstalling but still not working I am getting an error ( Snippet at the bottom ) , 

Ionic: 3.20.0

**What version of Streaming-Meda-Cordova-Plugin are you using?**
    "@ionic-native/streaming-media": "^4.9.0",
    "cordova-plugin-streaming-media": "^2.1.0",

**What version of Cordova are you using?**
8.0.0
**What devices are affected?**
While build .apk for android cordova-android: 7.0.0
**Please describe the issue in detail, with relevant code samples**

**What did you expect to happen?**

**What actually happened?**
BUILD FAILED in 8s
27 actionable tasks: 2 executed, 25 up-to-date
(node:19812) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: cmd: Command failed with exit code 1 Error output:
C:\Atrix\Projects\Football-union\testing\football-union_ test01\platforms\android\app\src\main\java\com\hutchind\cordova\plugins\streamingmedia\SimpleVideoStream.java:128: error: cannot find symbol
                StreamingMedia.callbackContext.sendPluginResult(StreamingMedia.onPause);
                                                                              ^
  symbol:   variable onPause
  location: class StreamingMedia
C:\Atrix\Projects\Football-union\testing\football-union_ test01\platforms\android\app\src\main\java\com\hutchind\cordova\plugins\streamingmedia\SimpleVideoStream.java:128: error: callbackContext has private access in StreamingMedia
                StreamingMedia.callbackContext.sendPluginResult(StreamingMedia.onPause);
                              ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s

**Comment by shamilovtim** [comment]
Fixed with v2.1.1
