### ISSUE TITLE
iOS: Video appears as black, can hear audio

### ISSUE THREAD

**Issue by petewalker** [nchutchind/cordova-plugin-streaming-media#141]
**What version of Streaming-Meda-Cordova-Plugin are you using?**

2.1.1

**What version of Cordova are you using?**

8.0.0

**What devices are affected?**

Any iOS device

**Please describe the issue in detail, with relevant code samples**

The change introduced in a recent commit here: https://github.com/nchutchind/cordova-plugin-streaming-media/commit/f4df91afa8013000cd853b90dd7e9ef3b90c01f5#diff-20cce6e98805983b2645e6b93b79a755R222

Means that any video you play is always covered with a black layer, as the video options do not allow customisation of an overlay (and I would not expect an overlay in video mode anyway..!)

Commenting out the linked line and the line below it make the video visible again.

**What did you expect to happen?**

Video plays successfully

**What actually happened?**

Audio plays, video is black

**Comment by shamilovtim** [comment]
v2.1.2 resolves this

**Comment by BardiaKh** [comment]
I know that you have marked this as closed but I have the same issue in v 2.1.2 on iOS devices.
When i play a movie, it's working like a charm. After that I open a music and its working ok, too. but when I open a movie after that, the movie is black but it has audio playback.

Does any body else have the same issue?

**Comment by shamilovtim** [comment]
I'll try to take a look this weekend

**Comment by BardiaKh** [comment]
Found the workaround. Submitted a PR for the fix.

**Comment by shamilovtim** [comment]
@BardiaKh thank you for taking care of this
