### ISSUE TITLE
Question - Video player not triggering OnClick

### ISSUE THREAD

**Issue by DSMTurboAWD** [nchutchind/cordova-plugin-streaming-media#143]
**What version of Streaming-Meda-Cordova-Plugin are you using?**
2.1.2
**What version of Cordova are you using?**
8.0.0
**What devices are affected?**
Android, Using the PhoneGap desktop application to serve up the code to a Samsung Galaxy S7

**Please describe the issue in detail, with relevant code samples**

_I have a feeling this is a simple issue that I am simply overlooking._
Like maybe not construction the function correctly, or understanding how to trigger the video player correctly.
I have stripped down the functions to eliminate any extra variables, but it is still not working.
As noted above I am using the PhoneGap desktop app to serve up the code and it builds without error, however, when trying to play the video, nothing happens.
Running it in a browser errors on the streaming media plugin:

    Uncaught TypeError: Cannot read property 'streamingMedia' of undefined
        at VideoPlaybackManager (app.js:129)
        at HTMLButtonElement.onclick (index.html?_ijt=d0vvubunpstjel9smj2o9iqhmi:1)

    // Here is the function in app.js
    var videoUrl = 'https://website.com/video.mp4';
    function VideoPlaybackManager() {
        alert('working!');
        window.plugins.streamingMedia.playVideo(videoUrl)
    }

    <!-- the HTML = part that calls up the video ->>
    <div class="video-container">
        <button onclick="VideoPlaybackManager()">TestVid</button>
    </div>

**What did you expect to happen?**

I was hoping that the onclick event would trigger the video player

**What actually happened?**

Nothing happens. The OnClick event does trigger the alert, but the video player never fires.

**Comment by shamilovtim** [comment]
Desktop app is not an actual mobile emulator. Use it on a native device phone or emulator.

**Comment by DSMTurboAWD** [comment]
Is not the PhoneGap application an emulator?
https://github.com/phonegap/phonegap-app-developer
https://phonegap.com/

I thought that was the whole idea of the Phonegap Application was to enable cross platform testing using the PhoneGap mechanism.

I will test with the Android Studio and see how that goes

**Comment by DSMTurboAWD** [comment]
I am not certain if this issue can be opened again, but it is still not working. 
Does this need to be an OnLoad, or Document Ready function?
I am not even able to trigger the player.
Is this supposed to trigger the hardware video player?

**Comment by shamilovtim** [comment]
If streamingMedia was coming back null it seems you aren't importing the plugin, thus don't have access to 'streamingMedia' variable. 

In Ionic / typescript we import the plugin at the top of our controller:
`import { StreamingMedia, StreamingVideoOptions, StreamingAudioOptions } from '@ionic-native/streaming-media';
`

In Cordova you do this differently, you will need to confirm how exactly you need to import in order to get access to the variable.

**Comment by DSMTurboAWD** [comment]
in cordova, I believe you just have to call it from the config.xml (though could be wrong I am fairly new at this)
    config.xml  
    `<plugin name="cordova-plugin-streaming-media" source="npm" spec="2.1.2" />`

mypage.html (using routes.js so individual pages do not have headers and such)

    <button onclick="VideoPlaybackManager();" >TestVid</button>    

app.js (note, not using an onload event, but the above onclick event, do I need to preload the player in the main head? This is where I am not sure as I am newer at this cordova method of developing mobile apps)

    var videoUrl = 'img/IMG_7813.mp4';
    function VideoPlaybackManager() {
        try {
           window.plugins.streamingMedia.playVideo(videoUrl);
        }
        catch (e) {
            alert('Something is not working right: ' + e.message);
        }
    }


This is the error I get: it is that it is not locating the video file?
![undefined](https://user-images.githubusercontent.com/2649649/42774882-8b46ab94-88f8-11e8-9730-2db77075f948.jpg)

**Comment by shamilovtim** [comment]
Your error means the plugin is not installed / being called properly. I recommend you do more research on how you use plugins in Cordova.

One example might be:

```
document.addEventListener("deviceready", onDeviceReady, false);
function onDeviceReady() {
    console.log(cordova.streamingMedia);
}
```

**Comment by DSMTurboAWD** [comment]
@shamilovtim Thank you for the assist. 
I was trying to load in the wrong order it seems. Everything is working now.
Thank you again
