### ISSUE TITLE
Video not playing at first launch.

### ISSUE THREAD

**Issue by Ahmedlag** [nchutchind/cordova-plugin-streaming-media#144]
Hello,

I'm having a small issue with the plugin when i try to playa video for the first time after the app launche it will never play and shows a black screen

I have to click on the (X) to close the view and reopen it again to get it working

Does anyone have the same issue ?

![screen shot 2018-07-16 at 18 22 37](https://user-images.githubusercontent.com/22698453/42771563-f9b62f6c-8927-11e8-92c9-019db165976e.png)

Plugin Version  : 2.1.2
Cordova : 8.0.0
Ionic : 3.2
iOS-Platform : 4.3

Iphone 6+

iOS : 11.0.3

**Comment by shamilovtim** [comment]
@Ahmedlag is the video remote or local? can you attach a link to the video? can you provide your code?

is it the iphone 6+ or the iphone 6+ emulator?

**Comment by Ahmedlag** [comment]
Hello @shamilovtim,

As i said, the video will work only if i call the : 
window.plugins.streamingMedia.playVideo(videoUrl, options);
again after i close the first, otherwise it shows the black screen i attched in the original post

The video is in a remote server, and the server is connected to a private network behind a firewall and a RP F5. 

the video format is mp4

The url forma is as the following :

https://registredemail:psw@medias.mywebsite.com/video.mp4 

I'm not using emulator, it isa real iphone 6+

I'll provide you the code tomorrow as the git is private as well :/

**Comment by shamilovtim** [comment]
I'm not sure we currently officially support this style of http path which is why you're hitting the problem

To debug I would try to access this video from a regular URL not behind a username/password.

**Comment by shamilovtim** [comment]
Same problem on Android?

**Comment by Ahmedlag** [comment]
Ok i'll try to stream a video without a username and psw and keep you up

Android always throws  : Unknown(1) - 1005

**Comment by Ahmedlag** [comment]
@shamilovtim 

Android 
I tried the direct link and it works, but not for the http path i've shared with you.
Strangely, it works perfectly with the V 0.1.4  of the plugin (yes i still have a copy)
i'll try to dig more in to it

iOS 
The first launche, i get this error in the xcode console 

 Warning: Attempt to present <AVPlayerViewController: 0x101093200> on <MainViewController: 0x10180a520> whose view is not in the window hierarchy!

But when i hit close and click the play button again, it works

**Comment by shamilovtim** [comment]
I should have a chance to investigate later this week

**Comment by shamilovtim** [comment]
@Ahmedlag I'm not sure I understand. Are you saying a standard HTTP URL works for Android and iOS or it doesn't?

**Comment by Ahmedlag** [comment]
@shamilovtim 
The standard HTTP URL works on both.

I think the problem is in my http path format.

This http path format requires a session to be created. Because when i play it from a desktop it asks me for user and psw even if they are in the url.

What triggers me is the iOS plugin can play the video but after a second try.

Anyway, thank you so much for your time.

**Comment by shamilovtim** [comment]
Awesome information, thanks.
