### ISSUE TITLE
Success callback should fire if closing the video early on iOS

### ISSUE THREAD

**Issue by html-rulez-d00d** [nchutchind/cordova-plugin-streaming-media#145]
**What version of Streaming-Meda-Cordova-Plugin are you using?** 
2.1.2

**What version of Cordova are you using?** 
8.0.0

**What devices are affected?** 
iOS (Android works)

**Please describe the issue in detail, with relevant code samples**

```
  // Play a video with callbacks
  var options = {
    successCallback: function() {
      //Confirmed this does not trigger on iOS. Unable to test the errorCallback.
    }
    ...
  };
  window.plugins.streamingMedia.playVideo(videoUrl, options);
```
**What did you expect to happen?**
options.successCallback should trigger so my dependent  javascript functions can be engaged.

**What actually happened?**
The callback does not trigger. This issue does not persist on Android. 
Tested on iOS:
- 4.5.5
- 4.5.4
- 4.4.0

Please let me know if you need of any other information and I will oblige. 

**EDIT:** After looking at your code, I see you are capturing the callback when the video ends. I was exiting the video before it completed, which would be a common user action. Would it be possible to trigger the success callback when the user exits the player before the video has finished?

**Comment by shamilovtim** [comment]
> Would it be possible to trigger the success callback when the user exits the player before the video has finished?

Yes it's possible. I'm not sure when I could provide this enhancement myself but I'd be happy to look at a PR if you want to do it.

**Comment by html-rulez-d00d** [comment]
I'm afraid I don't have much knowledge with iOS development, not do I have consistent access to a Mac.

My alternative was to use a JavaScript interval when playback occurred to periodically run the necessary upkeep functions (mainly to hide that status bar that keeps popping up and hanging around due to the player). Very hack-ish but it will do for now.

On Aug 7, 2018 7:11 PM, Timothy Shamilov <notifications@github.com> wrote:

Would it be possible to trigger the success callback when the user exits the player before the video has finished?

Yes it's possible. I'm not sure when I could provide this enhancement myself but I'd be happy to look at a PR if you want to do it.

**Comment by shamilovtim** [comment]
Is it correct to say that you're looking for the "Done" button to fire the Success callback and that it's currently not doing so?

Currently the success callback is being used as the termination callback of a video which was able to play successfully (entirely or partially). It should fire after a video has been successfully viewed, not upon first view, or partial view.

However the success callback is not currently intended to be fired when the video opens, or when other actions occur during the playing of the video.

**Comment by shamilovtim** [comment]
Update:

Apple doesn't provide a listener for the done button 🤬:
https://stackoverflow.com/questions/28671578/how-do-i-intercept-tapping-of-the-done-button-in-avplayerviewcontroller

Your use of a timer is the same solution that exists inside the native app and thus will be an acceptable stopgap until an Apple engineer corrects this issue

**Comment by html-rulez-d00d** [comment]
Well that is unfortunate (thanks Apple)! Oh well, like I said I have a "solution" to get me by in the mean time. Thank you

**Comment by MatthewPringle** [comment]
@html-rulez-d00d if you don't mind me asking, how are you using a timer to tell if the video is playing?

I was wanting successCallback to fire if someone closes the video part the way through and it doesn't seem to fire. What you described seems to be the same issue, if you wouldn't mind how did you solve it?

**Comment by html-rulez-d00d** [comment]
@MatthewPringle Greetings. So my issue also a bit of an issue with how the iOS status bar was being handled (whether it was by the plugin or by the OS). It would pop up when you would tap the screen and not disappear. 

My solution was to fire off an JS interval once the video started playing to try and clean up the status bar (using a separate plugin) every second or so. Clumsy and gross but it works (for now). I'm not sure if this approach would help you though. Perhaps put an event listener on the document / body to see when the user touches the screen and then register that as "complete"?

Additionally, outside of the status bar issue, I though it would be nice to actually determine when the user is done with the video (whether it's exiting prematurely or just following through the video entirely). Then you could, say fire off a request to your back-end to say said video had been watched by said user 100% or 80% or whatever.

**Comment by MatthewPringle** [comment]
@html-rulez-d00d I figured out, that for a portrait only app it still fires the orentationchange event when the landscape video is shown or hidden. Thats enough for me to be able to add a class when the video is showing in landscape.

**Comment by desmeit** [comment]
@html-rulez-d00d 
how did you handle the issue with the statusbar? you solved it with the setinterval?
But how did you detect when it should end?

Thanks

**Comment by rafiqvns** [comment]
Success callback function not calling if manually close the video in IOS.. any update this issue

**Comment by html-rulez-d00d** [comment]
@desmeit Sorry for the delay. Haven't been on github much lately. If I recall correctly, I simply let the interval run, constantly attempting to fix the statusbar issue I was having until the page refreshed. Not pretty, but got the job done in lieu of an actual callback.
