### ISSUE TITLE
Streaming Performance on Off Device Videos

### ISSUE THREAD

**Issue by DSMTurboAWD** [nchutchind/cordova-plugin-streaming-media#148]
**What version of Streaming-Meda-Cordova-Plugin are you using?**

2.1.2

**What version of Cordova are you using?**

7.1.0

**What devices are affected?**

Android 8.0+

**Please describe the issue in detail, with relevant code samples**

The performance of Streaming Media with OFF DEVICE videos is making it difficult to keep the media off device.

For example:
Using a local Azure Server on a 3GB connection to the virtual device. An 11 second video take 30 seconds to load, and plays start to finish without issue (though the 30 second load time)

Using a Web Server using WordPress as content management (so videos are hosted on WordPress). Videos never load. I've left it for 10+ minutes to just load the video and it never comes up.

Using An Amazon AWS S3 Bucket: Video takes ~2 minutes to load, but video will stutter, buffer, etc.

    function LoadVideo(videoUrl) {
        // Play a video with callbacks
        var options = {
            successCallback: function () {
                console.log("Video was closed without error.");
            },
            errorCallback: function (errMsg) {
                console.log("Error! " + errMsg);
            },
            orientation: 'landscape',
            shouldAutoClose: true,  // true(default)/false
            controls: true // true(default)/false. Used to hide controls on fullscreen
        };
        try {
            window.plugins.streamingMedia.playVideo(videoUrl, options);
        }
        catch (e) {
            alert('Something is not working right: ' + e.message);
            alert(videoUrl);
        }
    }

**What did you expect to happen?**

The video to buffer enough, and play without stuttering (to buffer)

**What actually happened?**
(see issue description)

**Comment by DSMTurboAWD** [comment]
These are primarily MP4 videos that I have hosted several locations.
I've tried several different videos that I have, but not tried other videos across the internet.
It just seemed odd because I've tried with several different video files across several different hosting services as laid out above.

I'll try another video

**Comment by shamilovtim** [comment]
In the past I have found random mp4 files online and streamed them with no
issues

**Comment by DSMTurboAWD** [comment]
I tested with this video:
http://www.html5videoplayer.net/videos/toystory.mp4

Perhaps it is simply that the video files are just too large. I will look into this, but it does not seem to be an issue with the plugin.

Sorry to bug folk :(
