### ISSUE TITLE
Android: Player controls hidden unexpectable

### ISSUE THREAD

**Issue by jmowitz** [nchutchind/cordova-plugin-streaming-media#155]
**What version of Streaming-Meda-Cordova-Plugin are you using?**

2.1.3

**What version of Cordova are you using?**

8.0.0

**What devices are affected?**

Android (tested on Samsung Galaxy)

**Please describe the issue in detail, with relevant code samples**

The video controls are hidden either automatically after 3 seconds or when touching outside of them. 

However, it does not seem like the 3 second timeout is cancelled when I manually touch to hide them.

That results in a strange behavior if I repeatedly hide / show then by touching on the screen. Old auto-hide timeouts may get triggered milliseconds after I have manually showed them.

**What did you expect to happen?**

Auto-hide timer to get cancelled when manually hiding the controls.

**What actually happened?**

Controls are hidden unexpectable.

**Comment by shamilovtim** [comment]
There is no intended touch to hide functionality currently in the plugin. Instead, there is only a touch to show action, which starts a 3 second timer to hide them again. If there's touch to hide functionality happening, then I'm not aware of it in my development build.

**Comment by jmowitz** [comment]
Ok, in that case maybe the touch to hide I'm seeing is probably a feature in android (because the controls are hidden when I touch outside of them). Anyway, probably not fixable in the plugin in that case.
