### ISSUE TITLE
Huge delay in the video stream

### ISSUE THREAD

**Issue by Floyd1256** [nchutchind/cordova-plugin-streaming-media#156]
**cordova-plugin-streaming-media version 1.0.2

**Cordova android version 6.2.3

**I am noticing a huge delay in the video stream. Comparing the results to the same stream being played on VLC, the delay between the VLC stream and the one in the app is around 3-4 seconds. Both are running on the same local network. Note that the native player on the mobile will keep loading for a few seconds before it begins to show the delayed video.

** Is there a way to reduce this delay? Usually in RTSP streams there is a way to define the delay time from the live video. Can that option be set anywhere?

**Comment by shamilovtim** [comment]
> **cordova-plugin-streaming-media version 1.0.2

You are using an outdated version of the plugin and cordova. Consider upgrading and see if the issue persists.

In order to receive an enhancement, you would need to update regardless.

**Comment by shamilovtim** [comment]
I am closing this for now. The code plays the video as soon as it's available using Android's lifecycle methods
