### ISSUE TITLE
bgImage No Longer Working with PhoneGap Build

### ISSUE THREAD

**Issue by Henryisthebest** [nchutchind/cordova-plugin-streaming-media#162]
Repoening issue #27

There is no background image being shown on either iOS or Android anymore. I will try upload a screenshot. 

Even the controls are not visible until you click on the blank screen.

**Comment by Henryisthebest** [comment]
There are more details in issue #27

**Comment by shamilovtim** [comment]
Please use the template for an issue

**Comment by shamilovtim** [comment]
What is the version of the plugin in package.json?

This functionality works as expected in the latest version

**Comment by shamilovtim** [comment]
also: post the code that's causing the issue
