### ISSUE TITLE
Cannot release on App Store if using PGB 

### ISSUE THREAD

**Issue by juliabat** [nchutchind/cordova-plugin-streaming-media#165]
Hey
I am are experiencing the same problem as the user in issue #101, i.e. that the addition of background audio in the plist is preventing me from pulishing in the Apple App Store. 
I don't see any way of removing the background audio permissions once they are added with this plugin's plugin.xml  (when using PhoneGap Build). 

Using edit-config  to modify the plist in our app's config.xml does not seem to work: the resulting plist still contains the background-audio configurations once built with PGB.

Maybe this plugin should have a possible configuration for whether or not background audio is supported?

Cheers

**Comment by shamilovtim** [comment]
Will need to move to modular approach with npm postinstall scripts as noted here: https://github.com/dpa99c/cordova-diagnostic-plugin#specifying-modules

If you need to hotfix this for now just remove the keys from plugin.xml by forking this plugin and referencing your fork directly by git url in your package.json

**Comment by shamilovtim** [comment]
One other way of fixing this quickly is intentionally allowing your videos to play in the background. You can do this by using playAudio to play your videos.

**Comment by Angelk90** [comment]
Hi, @shamilovtim are you now taking care of the project?
I realized the existence of a small problem that happens on certain devices.
If you publish the solution and the type of problem, you could update the version located on npm, so I solved the problem without having to create my own version.

**Comment by shamilovtim** [comment]
I am the maintainer, yes. If you have an issue please open a ticket

**Comment by Angelk90** [comment]
@shamilovtim : I did as you said, I hope you will soon merge and publish on npm. #166

**Comment by shamilovtim** [comment]
Until Cordova provides a way of using conditionals in plugin.xml files I just don't see any sane way of handling this problem other than letting your videos play in the background or forking this plugin. The reality is far more people need background audio than will have this problem from Apple

**Comment by dann95** [comment]
For who have problems with background audio permission, and don't need it, just do:

config.xml in ios section:
<hook src="hooks/audiohook.js" type="after_platform_add" />


hooks/audiohook.js
```js
const fs = require('fs'),
    path = require('path'),
    plist = require('plist'),
    filePATH = path.join(__dirname, '..', 'platforms', 'ios', 'AppName', 'AppName-Info.plist'),
    plistFILE = fs.readFileSync(filePATH, "utf8"),
    parsedPLIST = plist.parse(plistFILE);

if (parsedPLIST.UIBackgroundModes) {
    parsedPLIST.UIBackgroundModes = parsedPLIST.UIBackgroundModes
        .filter(mode => mode !== 'audio');
}

fs.writeFileSync(filePATH, plist.build(parsedPLIST), {
    encoding: "utf8"
});

```
