### ISSUE TITLE
Unhandled exception on iOS < 11

### ISSUE THREAD

**Issue by Gazer** [nchutchind/cordova-plugin-streaming-media#168]
It seems that the logic for disabling the gestures is not compatible with iOS 10 or lower. I was having a problem to load videos on iOS 10 and the exception happens on `StreamingMedia.m` at line 284:

```
UIView *contentView = [moviePlayer.view valueForKey:@"contentView"];
```

Commenting the code of `handleGestures` fixes the problem. I've tried to figure out how to fix it but my iOS knowledge if very limited :)

**Comment by shamilovtim** [comment]
My apologies but I can't provide support for iOS 10 and lower 😅 . You are welcome to pull the version of the plugin which did support those lower versions:

`npm install git+https://github.com/nchutchind/cordova-plugin-streaming-media.git#v.2.1.3`

Releases page:
https://github.com/nchutchind/cordova-plugin-streaming-media/releases

Good luck!

**Comment by Gazer** [comment]
@shamilovtim that makes sense! I just want to report just in case other users have the same problem.

Maybe updating the README will help in the meantime? Right now it says:

```
Uses the AVPlayerViewController, supported for iOS 9+.
```

**Comment by shamilovtim** [comment]
Done! Much appreciated.
