### ISSUE TITLE
ShouldAutoClose is 'false' by default on Android, 'true' on iOS

### ISSUE THREAD

**Issue by maheee** [nchutchind/cordova-plugin-streaming-media#17]
In SimpleVideoStream.java, lines 42 and 43 you have these lines:

> mShouldAutoClose = b.getBoolean("shouldAutoClose");
> mShouldAutoClose = mShouldAutoClose == null ? true : mShouldAutoClose;

'getBoolean' returns 'false' if the key isn't set so the default is always 'false'. Replacing it with this should fix the issue:

> mShouldAutoClose = b.getBoolean("shouldAutoClose", true);

http://developer.android.com/reference/android/os/Bundle.html#getBoolean%28java.lang.String,%20boolean%29

**Comment by faceleg** [comment]
Please feel free to submit a PR.
