### ISSUE TITLE
playVideo throw NSException exception in ios

### ISSUE THREAD

**Issue by SRV-Garg** [nchutchind/cordova-plugin-streaming-media#173]
I am using this plugin inside my ionic 3 application with ionic-native on android it is working fine but with ios i am getting following exception

Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<AVPlayerView 0x1685c680> valueForUndefinedKey:]: this class is not key value coding-compliant for the key contentView.'

Plugin version : 2.2.0
Ionic version :  3.19.1
Cordova version: 8.0.0 

Plugin used with app
card.io.cordova.mobilesdk 2.1.0 "CardIO"
com.paypal.cordova.mobilesdk 3.5.0 "PayPalMobile"
cordova-admob-sdk 0.22.0 "AdMob SDK"
cordova-custom-config 5.0.3 "cordova-custom-config"
cordova-plugin-admob-free 0.25.0 "Cordova AdMob Plugin"
cordova-plugin-android-permissions 1.0.0 "Permissions"
cordova-plugin-audiotoggle 1.0.3 "cordova-plugin-audiotoggle"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-fcm-with-dependecy-updated 2.4.0 "Cordova FCM Push Plugin"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-ionic-webview 1.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-iosrtc 4.0.2 "iosrtc"
cordova-plugin-media 5.0.2 "Media"
cordova-plugin-media-capture 3.0.2 "Capture"
cordova-plugin-nativeaudio 3.0.9 "Cordova Native Audio"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-screen-orientation 3.0.1 "Screen Orientation"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-streaming-media 2.2.0 "StreamingMedia"
cordova-plugin-video-editor 1.1.3 "VideoEditor"
cordova-plugin-websocket 0.12.2 "WebSocket for Android"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-promise-polyfill 0.0.2 "cordova-promise-polyfill"
cordova-sqlite-storage 2.6.0 "Cordova sqlite storage plugin"
es6-promise-plugin 4.2.2 "Promise"
ionic-plugin-keyboard 2.2.1 "Keyboard"

Complete logs from xcode 
2019-02-04 12:11:00.117696+0530 RiiG3N[617:78896] playvideo called
2019-02-04 12:11:00.118279+0530 RiiG3N[617:78896] play called
2019-02-04 12:11:00.118428+0530 RiiG3N[617:78896] Clean up called
2019-02-04 12:11:00.118551+0530 RiiG3N[617:78896] startplayer called
2019-02-04 12:11:00.432240+0530 RiiG3N[617:78896] *** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<AVPlayerView 0x1685c680> valueForUndefinedKey:]: this class is not key value coding-compliant for the key contentView.'
*** First throw call stack:
(0x1ca8bb3d 0x1bd13067 0x1ca8b84f 0x1d395153 0x1d2ed505 0x1594d9 0x158ab1 0x157815 0x157a39 0x248d41 0x116475 0x1162c7 0x117c13 0x24f67d63 0x24f1014b 0x24f11b67 0x24f11aaf 0x24f11a25 0x24da207b 0x24ef4b41 0x24d7552d 0x24d77521 0x208f4c5b 0x208f4e0f 0x1ca47fdd 0x1ca47b05 0x1ca45f51 0x1c9991af 0x1c998fd1 0x1e143b41 0x21d21a53 0xd9a93 0x1c1864eb)
libc++abi.dylib: terminating with uncaught exception of type NSException

I am testing this in actual device iphone 5s version 10.3.3

**Comment by SRV-Garg** [comment]
@shamilovtim Thank you for your suggestion, I want to know that the older version will also work with the current IOS version or not?

**Comment by wing505** [comment]
@SRV-Garg Version 2.1.3 is available.

**Comment by shamilovtim** [comment]
Yeah there's almost certainly a version for you, since the plugin is several years old. Just check out the versions in the version history.
