### ISSUE TITLE
MediaPlayer Error: Unknown (1) -2147483648

### ISSUE THREAD

**Issue by Pantic14** [nchutchind/cordova-plugin-streaming-media#176]
**What version of Streaming-Meda-Cordova-Plugin are you using?**
Last

**What version of Cordova are you using?**
Ionic 4 - Cordova 8.1.1

**What devices are affected?**
All

**Please describe the issue in detail, with relevant code samples**
When i try to reproduce a video callback a error "MediaPlayer Error: Unknown (1) -2147483648"

**What did you expect to happen?**
Reproduce Video

**What actually happened?**
Callback a error

**Comment by heimi** [comment]
I have got this problem, version is 2.2.0

**Comment by shamilovtim** [comment]
Hello, could you please post the code that's causing the issue?

**Comment by heimi** [comment]
I just use the usage code:

var videoUrl = "rtsp://192.168.160.133:554/mpeg4?username=admin&password=E10ADC3949BA59ABBE56E057F20F883E";
var options = {
    successCallback: function() {
      alert("Video was closed without error.");
    },
    errorCallback: function(errMsg) {
      alert("Error! " + errMsg);
    },
    orientation: 'landscape',
    shouldAutoClose: false,  // true(default)/false
    controls: true // true(default)/false. Used to hide controls on fullscreen
  };
  // Just play a video
  window.plugins.streamingMedia.playVideo(videoUrl,options);

**Comment by heimi** [comment]
https://developer.android.com/guide/topics/media/media-formats
Is the media not meet the "Video streaming requirements"?

**Comment by shamilovtim** [comment]
@heimi Hi, sorry for the late response! We don't support RTSP in this plugin right now. You'll have to link directly to a video file with http://.
