### ISSUE TITLE
is it possible to add title/description when playing audio?

### ISSUE THREAD

**Issue by vineshhpatel** [nchutchind/cordova-plugin-streaming-media#179]
**What version of Streaming-Meda-Cordova-Plugin are you using?**
2.2.0
**What version of Cordova are you using?**
cordova 8.0.0
I'm using Ionic 3. 
**What devices are affected?**
All
**Please describe the issue in detail, with relevant code samples**
Plugin should have an option to display audio title and/or description when it's playing.

`var optionsStreamingMedia = {

          successCallback: function () {
          console.log("audio was closed without error.");
      },
      errorCallback: function (errMsg) {
        console.log("Error! " + errMsg);
      },
      bgColor: "#192651",
      bgImage: REMOTE_IMG_URL,
      bgImageScale: "fit",
      initFullscreen: false,
      shouldAutoClose: true,  
      controls: false
    };
    this.streamingMedia.playAudio(AUDIO_URL, optionsStreamingMedia);`

sorry for the formatting of the code. I tried but the first link messes up the formatting of code block. 
**What did you expect to happen?**
It should have an option for title and description of audio.
**What actually happened?**
does not display audio's title or description when playing it.

**Comment by shamilovtim** [comment]
hello. this is a native iOS video player. there is no place that i know of that native video players offer in order to have a title / description. when Apple or Android offer a title and decription then i'll add those features. best of luck to you
