### ISSUE TITLE
Need an option to play video on both screen TV and iPad during AirPlay

### ISSUE THREAD

**Issue by emranashraf** [nchutchind/cordova-plugin-streaming-media#180]
**What version of Streaming-Meda-Cordova-Plugin are you using?**
2.2.0

**What version of Cordova are you using?**
8.1.2

**What devices are affected?**
iPad

**Please describe the issue in detail, with relevant code samples**
I need to play video on both screens simultaneously on both screens iPad and TV during AirPlay. How can I achieve it? Right now when we play video on Airplay it just runs on TV.

**What did you expect to happen?**

**What actually happened?**

**Comment by shamilovtim** [comment]
this isn't possible at the moment, and that's a limitation that comes directly from Apple's AirPlay rather than anything the plugin itself is limiting
