### ISSUE TITLE
not able to play local stored video in ios 

### ISSUE THREAD

**Issue by ravi9376** [nchutchind/cordova-plugin-streaming-media#183]
**What version of Streaming-Meda-Cordova-Plugin are you using?**
cordova-plugin-streaming-media@2.2.0",
**What version of Cordova are you using?**
"@angular/common": "^7.2.2",
    "@angular/core": "^7.2.2",
    "@angular/forms": "^7.2.2",
    "@angular/http": "^7.2.2",
    "@angular/platform-browser": "^7.2.2",
    "@angular/platform-browser-dynamic": "^7.2.2",
    "@angular/router": "^7.2.2",
    "@ionic-native/core": "^5.0.0",
    "@ionic-native/file": "^5.5.1",
    "@ionic-native/file-transfer": "^5.5.1",
    "@ionic-native/ionic-webview": "^5.5.1",
    "@ionic-native/splash-screen": "^5.0.0",
    "@ionic-native/status-bar": "^5.0.0",
    "@ionic-native/streaming-media": "^5.5.1",
    "@ionic/angular": "^4.1.0",
    "cordova-android": "8.0.0",
    "cordova-ios": "4.5.5",
    "cordova-plugin-file": "^6.0.1",
    "cordova-plugin-file-transfer": "^1.7.1",
    "cordova-plugin-streaming-media": "^2.2.0",
    "core-js": "^2.5.4",
    "rxjs": "~6.5.1",
    "tslib": "^1.9.0",
    "zone.js": "~0.8.29"
**What devices are affected?**
ios
**Please describe the issue in detail, with relevant code samples**
  showVideo1(title) {
    const options = {
      successCallback() {
        console.log('Video was closed without error.');
      },
      errorCallback(errMsg) {
        console.log('Error! ' + errMsg);
      },
      orientation: 'landscape',
      shouldAutoClose: true, // true(default)/false
      controls: true // true(default)/false. Used to hide controls on fullscreen
    };
    this.streamingMedia.playVideo(
      this.file.documentsDirectory + 'Videos/' + title,
      options
    );
  }
i m unable to access video from local i had already tried from local applicationDirectory but didnot work in ios 
**What did you expect to happen?**

**What actually happened?**

**Comment by shamilovtim** [comment]
this isn't a problem with the plugin. i recommend you seek support from ionic or cordova's resources in order to get your pathing correct
