### ISSUE TITLE
MediaPlayer Error: Unknown (1) -2147483648

### ISSUE THREAD

**Issue by ShengChangWei** [nchutchind/cordova-plugin-streaming-media#187]
**What version of Streaming-Meda-Cordova-Plugin are you using?**

**What version of Cordova are you using?**

**What devices are affected?**

**Please describe the issue in detail, with relevant code samples**

**What did you expect to happen?**

**What actually happened?**

**Comment by psbsp** [comment]
I am facing same issue. android version 10 and am using localhost url
