### ISSUE TITLE
Error while trying to stream from youtube

### ISSUE THREAD

**Issue by gotters** [nchutchind/cordova-plugin-streaming-media#207]
**What version of Streaming-Meda-Cordova-Plugin are you using?**
5.13.0

**What version of Cordova are you using?**
Cordova Android 8 

**What devices are affected?**
Android (only tried it there so far)

**Please describe the issue in detail, with relevant code samples**
Simply trying to stream a video of youtube. It switches to landscape and the loader icon starts showing but then just closes and logs an exception to the console. Below is the console log which includes the url and the exception.
If I switch to a different link for eg http://techslides.com/demos/sample-videos/small.mp4 then it works!!?
Console.log
**Error streaming https://www.youtube.com/embed/BFPf7wrLWxg?ecver=2&autoplay=1
MediaPlayer Error: Unknown (1) -2147483648**

Code below: (Tried it with both autoplay = 1 and without)
  ```
playVideo(video){
    let options: StreamingVideoOptions = {
      successCallback: () => { console.log('Video played') },
      errorCallback: (e) => { console.log('Error streaming',e) },
      orientation: 'landscape',
      shouldAutoClose: false,
      controls: true
    };
    
    console.log('Playing ',video.videoLink + '&autoplay=1');

    this.streamingMedia.playVideo(video.videoLink + '&autoplay=1', options);
  }
```
**What did you expect to happen?**
The video should start streaming and play right away

**What actually happened?**
Switches to landscape, something starts loading and then just switches out back to previous app view.

**Comment by shamilovtim** [comment]
This isn't a YouTube plugin. YouTube isn't a site that you can just stream video from, it's a social media platform. You'll need to use YouTube's players.
