### ISSUE TITLE
plugin unsupported: com.hutchind.cordova.plugins.streamingmedia @ 0.1.4

### ISSUE THREAD

**Issue by bcolflesh** [nchutchind/cordova-plugin-streaming-media#21]
Adobe's Phonegap Build service doesn't like the latest version:

"plugin unsupported: com.hutchind.cordova.plugins.streamingmedia @ 0.1.4"

Not specifying a version provides 0.1.3 with no error.

**Comment by faceleg** [comment]
Please try with the latest version.
