### ISSUE TITLE
Success and Failure callback not getting called in iOS

### ISSUE THREAD

**Issue by sarath-vijay** [nchutchind/cordova-plugin-streaming-media#216]
`  const options: StreamingVideoOptions = {`
     ` successCallback: () => {`
        `console.log("**************** SUCCESS");`
     ` },`
     ` errorCallback: (e) => {`
        `console.log("****************" + e);`
     ` },`
      `orientation: 'potrait',`
      `shouldAutoClose: true,`
     ` controls: true,`
   ` };`
` this.streamingMedia.playVideo(this.videoUrl, options);`

I have implemented this. But I am not getting either success or Failure callback in iOS devices. I tested this in iPhone7(iOS 13.x). Can you please help with this.

**Comment by richpixel** [comment]
I implemented this solution in the iOS plugin code to address this:
https://stackoverflow.com/questions/38565412/done-button-click-event-in-avplayerviewcontroller
