### ISSUE TITLE
iPhone hardware mute silences the palyback

### ISSUE THREAD

**Issue by vkhazin** [nchutchind/cordova-plugin-streaming-media#26]
When iPhone hardware mute button is toggled - the video will play silent.

Is there a way enable sound for the playback in the plugin or, ideally, let JavaScript to control the behaviour of hardware mute button?

**Comment by guicouto** [comment]
I'm with the same problem.Can you fixed it? @vkhazin

**Comment by vkhazin** [comment]
Sorry did not - known issue.

On Wednesday, 30 December 2015, Guilherme da Costa Couto <
notifications@github.com> wrote:

> I'm with the same problem.Can you fixed it? @vkhazin
> <https://github.com/vkhazin>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nchutchind/Streaming-Media-Cordova-Plugin/issues/26#issuecomment-168067324>
> .
>


-- 
Sincerely yours,
Vlad Khazin
Email: vlad.khazin@icssolutions.ca
Skype: vladimir.khazin
Cell: 416-802-2771
Fax: 866-425-2660

<http://www.linkedin.com/in/vkhazin>

**Comment by Kailash43** [comment]
Do anyone resolved this **issue**???

**Comment by vkhazin** [comment]
I have switched to native html5 video player using:
https://github.com/Wildhoney/ngVideo and did not yet have chance to confirm
whether mute button has been resolved - I have switched for the playback
events shall be sent back to the app reason.

On Mon, May 9, 2016 at 12:00 AM, Kailash43 <notifications@github.com> wrote:

> Do anyone resolved this *issue*???
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/nchutchind/cordova-plugin-streaming-media/issues/26#issuecomment-217771565>
>



-- 
Sincerely yours,
Vlad Khazin
Email: vlad.khazin@icssolutions.ca
Skype: vladimir.khazin
Cell: 1 (416) 802-2771
Fax: 1 (289) 963-4864

<http://www.linkedin.com/in/vkhazin>

**Comment by shamilovtim** [comment]
Resolved with latest PR
