### ISSUE TITLE
bgImage No Longer Working with PhoneGap Build

### ISSUE THREAD

**Issue by bcolflesh** [nchutchind/cordova-plugin-streaming-media#27]
bgImage: "<SWEET_BACKGROUND_IMAGE>" - option no longer displays images when built with latest version of PhoneGap Build.

**Comment by Henryisthebest** [comment]
I am still having this problem - was there a fix to this??

**Comment by shamilovtim** [comment]
@Henryisthebest Did you pull down the latest version? This was fixed a while back. Please open a new issue

**Comment by Henryisthebest** [comment]
I just dowloaded the plugin.  I'm using it in an  ionic v1 app... but with the latest Cordova etc

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Henryisthebest** [comment]
Ionic:

   ionic (Ionic CLI) : 4.1.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework   : ionic1 1.2.4
   @ionic/v1-toolkit : 1.0.8

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 6.4.0, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 2.1.4, (and 15 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/ginil/Library/Android/sdk)
   ios-deploy        : 2.0.0
   ios-sim           : 5.0.3
   NodeJS            : v6.9.1 (/usr/local/bin/node)
   npm               : 3.10.8
   OS                : macOS High Sierra
   Xcode             : Xcode 10.0 Build version 10A255

**Comment by shamilovtim** [comment]
What platform is the problem on?

Please open a new ticket, this one is from 2015.

**Comment by Henryisthebest** [comment]
Hi – it’s on both iOS and Android. I’ll open a new ticket. Thanks

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
