### ISSUE TITLE
Not working in iOS

### ISSUE THREAD

**Issue by mayurloved** [nchutchind/cordova-plugin-streaming-media#28]
Hello i have install plugin using cli.
But when i use yotube url then it open player but not playing video its loading nothing Ahed
Please help me.

**Comment by carsonip** [comment]
@mayurloved: For youtube videos, you may want to check this out: https://github.com/Glitchbone/CordovaYoutubeVideoPlayer

**Comment by faceleg** [comment]
Please reopen if you're willing to provide more information.
