### ISSUE TITLE
Video not playing on iOS

### ISSUE THREAD

**Issue by lorthirk** [nchutchind/cordova-plugin-streaming-media#29]
Hello, I have a weird issue in iOS 8. I'm open an rtsp:// link and, while in Android I have no problems, in iOS I only get a black screen with media controls (volume, play, next, previous) and an endless "Loading..." with a spinner.

Am I doing someting wrong? Maybe rtsp is not supported in iOS8?

**Comment by DiegoZurita** [comment]
I think that is no problem with the plugin, but with the protocol, because rtsp in based in flash, and iOS hate flash, so ios's devices does not support Flash, maybe by that reason you only can see the loading spin.

**Comment by Lorthirk** [comment]
I'm sorry but I have to strongly disagree. RTSP has no relations with Flash whatsoever. It's a network protocol, similar in some ways to HTTP.

**Comment by DiegoZurita** [comment]
Ow, really, really, i got confused with the RTMP protocol. In this case i dont know what can be. Sorry.

**Comment by longquan77** [comment]
hello , this plugin supports MMS protocl?

**Comment by faceleg** [comment]
So far this plugin officially supports files only.

**Comment by zhouzhongyuan** [comment]
@Lorthirk Do you resolve this problem? I have the same problem with you.

**Comment by Lorthirk** [comment]
@zhouzhongyuan no, I didn't because I lost interest for this feature. However, it seems that new versions of the plugin supports RTSP streaming on iOS but again, I did not test it.

**Comment by zhouzhongyuan** [comment]
@Lorthirk Thank you.

**Comment by shamilovtim** [comment]
no current official support for rtsp
