### ISSUE TITLE
Unknown error on Android 4.1.1

### ISSUE THREAD

**Issue by jorisw** [nchutchind/cordova-plugin-streaming-media#30]
If I play a video with a remote URL on Android 4.4.1, this happens:

```
App is being put in the background.
Error! MediaPlayer Error: Unknown (1) -2147483648
App is being restored to the foreground.
```

The first and third lines are my debug lines when the app is suspended and resumed respectively.

Since my app has all kinds of functionality attached to suspend/resume, I cannot use this plug-in.

**Comment by saratonite** [comment]
facing the same issue (Kitkat)

**Comment by gabrielpotumati** [comment]
same issue (android 6)

**Comment by Maikell84** [comment]
I can confirm this issue on Android 4.4 and Android 5.1

**Comment by stoy** [comment]
I confirm this issue on Android 5.1 too

**Comment by ohadbp** [comment]
Did any of you guys manage so solve/work-around this problem? I am having same issue with some of the URLs i am trying to play (some does work, others throw the same error mentioned above)

**Comment by stoy** [comment]
No sorry, we changed project environement cause of this. we don't use cordova anymore (we use native platforme now)

**Comment by ohadbp** [comment]
Ok, the problem for me was with the encoding of the mp4 file - While the browser and VLC didn't mind the invalid encoding, quicktime player and mobile (both android and ios) couldn't play and throw errors.

Once i fixed the files i manage to stream them successfully. See URL below to what valid mp4 file is:

http://arkanis.de/weblog/2010-08-05-creating-a-valid-and-working-mp4-video
