### ISSUE TITLE
RTSP stream on iOS

### ISSUE THREAD

**Issue by dsbcourtney** [nchutchind/cordova-plugin-streaming-media#31]
Should this work with an RTSP url within iOS? It loads up the video player but nothing seems to stream. The url works fine embedded in web page and in VLC player.

Thanks

**Comment by schnti** [comment]
I have the same problem. However, the stream is not working well in VLC iOS. VLC OS X Stream works.

**Comment by Zorgatone** [comment]
iOS doesn't support RTSP unfortunately.. I'm looking for a plugin that would play that

**Comment by recaisinekli** [comment]
Here is a solution to play RTSP on iOS based on VXG Video Player SDK. https://github.com/recaisinekli/rtspPlayer
