### ISSUE TITLE
Unable to play video on 3G or LTE service

### ISSUE THREAD

**Issue by yashprit** [nchutchind/cordova-plugin-streaming-media#32]
Awesome work on plugin.

We are using this plugin for our app, but on WIFI its working fine, while 3G or LTE network without any error it silently close itself. 

Could you please let us, what could be wrong here, if you can guide me I can look myself and can send you pull request.

**Comment by maxroom** [comment]
why closed? the same question, and i use the latest version, but still have this issue

**Comment by shamilovtim** [comment]
@maxroom can you open a new ticket? this one has no details and we have a template for information we want to get from you
