### ISSUE TITLE
force play in landscape

### ISSUE THREAD

**Issue by maoamid** [nchutchind/cordova-plugin-streaming-media#39]
Is someone using this player with device orientation plugin? The player is playing well for me, thanks a lot; my app use portrait orientation. How can I force to play items in fullscreen lanscape? is there a hidden player option?

**Comment by miguepiscy** [comment]
In this pull request add option orientation: 'landscape', only work in android
https://github.com/nchutchind/Streaming-Media-Cordova-Plugin/pull/41

**Comment by maoamid** [comment]
thank you. For me is enough as I use it for rtsp live stream only on android under v5.
