### ISSUE TITLE
initial setting

### ISSUE THREAD

**Issue by gabrielpotumati** [nchutchind/cordova-plugin-streaming-media#43]
Hello I am struggling to make it work, I'm using XDK, and imported the repository and added the script:
function video(){
    var videoUrl = "rtsp://streaming.xxxxxx.com.br:1935/xxxx/xxxxx";
  // Just play a video
  window.plugins.streamingMedia.playVideo(videoUrl);

  // Play a video with callbacks
  var options = {
    successCallback: function() {
      alert("Video was closed without error.");
    },
    errorCallback: function(errMsg) {
      alert("Error! " + errMsg);
    }
  };
  window.plugins.streamingMedia.playVideo(videoUrl, options);  
}

but nothing happens .. Anyone know what else left to do?

**Comment by ashishbajaj99** [comment]
Did you get this working - our team is also facing this same issue...
