### ISSUE TITLE
IOS 6 video player doesnt gets back to app after video is played and hangs the app

### ISSUE THREAD

**Issue by indranil-m** [nchutchind/cordova-plugin-streaming-media#5]
in IOS 6  when I tapped on video and ran it through streaming media plugin it doesnt gets back to app after video is played and hangs the app.

**Comment by ademc** [comment]
This issue takes my hours and finally i found the problem. Is the video/audio url contains non-english character (ğ,ü,ş,i,ö,ç etc) plugin does not play without any error message but actually can not access the real path.
To fix this encode url  before use as parameter.

window.plugins.streamingMedia.playVideo(videoUrl);

to

window.plugins.streamingMedia.playVideo(encodeURI(videoUrl));
