### ISSUE TITLE
Video not able to play in iPad ios 9.2?

### ISSUE THREAD

**Issue by Kailash43** [nchutchind/cordova-plugin-streaming-media#56]
I am using **Streaming-Meda-Cordova-Plugin version 0.1.4** for playing videos.

My **Cordova** version is **6.0.0**

It is **not playing in iPad which has an IOS 9.2 version**. but it **works well in** my iPhone which has an **IOS 7.0 version**.

I am passing on my video path just by one simple line of code.

**window.plugins.streamingMedia.playVideo(path);**

It works pretty well in Android device and IOS mobile phones.
But not in iPad.
Even i tried to check the console for the path. so that there should not be path issue but it display the correct path in iPad console after debugging. When i click on play button there is no response it is not even showing the default video player.

Even i want to know why the sound is not coming while the hardware mute button is enable in IOS devices?

Can you help me to figure out what exactly the issue is and how to resolve it?

**Comment by Kennyhp** [comment]
Hello, I have the same problem. Did you found any solution? @Kailash43

**Comment by Kailash43** [comment]
@Kennyhp nope i didn't got any solution for this issue.

**Comment by Harris-Aaron** [comment]
I have the same problem,😢. It can't run on iOS,  I try to use HTML5 video!
