### ISSUE TITLE
Not really an issue, but are there any plans for manipulating the "forward" and "back" buttons in the media player?

### ISSUE THREAD

**Issue by hograinwheat** [nchutchind/cordova-plugin-streaming-media#6]
Great job on the plug-in by the way, it's working great in iOS 7.

**Comment by ahmu83** [comment]
Will it be difficult to add a close button on the video play mode? The only way to close a video stream on android is to hit the back button. Thanks for the great plugin.

**Comment by faceleg** [comment]
No plans to support this. If someone wants to submit a PR, great!
