### ISSUE TITLE
Error: Unknown (1) -2147483648

### ISSUE THREAD

**Issue by JohnRSim** [nchutchind/cordova-plugin-streaming-media#62]
**What version of Streaming-Meda-Cordova-Plugin are you using?**
1.0.2

**What version of Cordova are you using?**
Cordova 6.x

**What devices are affected?**
Android 5.x - Samsung S6

**Please describe the issue in detail, with relevant code samples**
``javascript
  var videoUrl = 'rtsp://192.168.1.125:554/live';

  // Play a video with callbacks
  var options = {
    successCallback: function() {
      console.log("Video was closed without error.");
    },
    errorCallback: function(errMsg) {
      console.log("Error! " + errMsg);
    },
    orientation: 'landscape'
  };
  window.plugins.streamingMedia.playVideo(videoUrl, options);
``

**What did you expect to happen?**
Video to stream - shows loading and then errors 

**What actually happened?**
Error! MediaPlayer Error: Unknown (1) -2147483648

**Comment by faceleg** [comment]
Can you please check this answer http://stackoverflow.com/a/18084143/187954 and close this issue if you find it's a codec related problem?

**Comment by asoare** [comment]
I am getting the same error when trying to play this video:

var videoUrl = 'https://username:password@link';

works on Android 4.1 (Samsung) & Android 4.4.2 (HTC, Asus) but not on Android 5.x (Samsung, Huaweii) or 6.x (Nexus)

**Comment by rachelxi** [comment]
Probably check the permission for this app on android system?

**Comment by TahaSeckin** [comment]
I have the same problem. did anyone find a solution

**Comment by TahaSeckin** [comment]
@JohnRSim  I have the same problem. did anyone find a solution.

**Comment by shamilovtim** [comment]
Plugin does not currently support rtsp video
