### ISSUE TITLE
Can anyone help for iOS warning

### ISSUE THREAD

**Issue by riteish08** [nchutchind/cordova-plugin-streaming-media#63]
Installed plugin successfully.

Working fine on Android Device, but on iOS device its showing Warning in XCode

![2016-06-4](https://cloud.githubusercontent.com/assets/19775559/15818647/31b566f2-2bfc-11e6-844f-de9a9edad1eb.png)

Please help me in this as i am a newbie for this

**Comment by Harris-Aaron** [comment]
My program can not run on the Ios, but in the Android can see the surveillance video stream
