### ISSUE TITLE
Error: undefined is not an object (evaluating 'window.plugins.streamingMedia')

### ISSUE THREAD

**Issue by tranduytan248** [nchutchind/cordova-plugin-streaming-media#65]
Hi, 
I added plugin, and add code demo, but it show error
Error: undefined is not an object (evaluating 'window.plugins.streamingMedia')
How to fix it?
Thank,

**What version of Streaming-Meda-Cordova-Plugin are you using?**

**What version of Cordova are you using?**

**What devices are affected?**

**Please describe the issue in detail, with relevant code samples**

**What did you expect to happen?**

**What actually happened?**

**Comment by faceleg** [comment]
Do you wait for deviceReady event?

**Comment by ParVisual** [comment]
Handle the "playVideo" in deviceready event. 
Try building and testing in a real device.
