### ISSUE TITLE
How to play video local in device?

### ISSUE THREAD

**Issue by tranduytan248** [nchutchind/cordova-plugin-streaming-media#66]
Hi!
How to play video local in device?

**What version of Streaming-Meda-Cordova-Plugin are you using?**

**What version of Cordova are you using?**

**What devices are affected?**

**Please describe the issue in detail, with relevant code samples**

**What did you expect to happen?**

**What actually happened?**

**Comment by zabojad** [comment]
Have you tried this: http://stackoverflow.com/a/36573687/1255091 ?

**Comment by zabojad** [comment]
It works on Android but not on iOS...

**Comment by zabojad** [comment]
@faceleg @nchutchind would that be possible to add support for local video files playback? Like files located under `/www` and `file:///var/mobile/Containers/Data/Application/XXX/Documents`?

**Comment by lauron** [comment]
I have been trying to locate information on how to use the plugin to play video from local ios storage,  under /www path. Has there been any progress here? Playing video using an external URL works fine.

**Comment by MontyZhao** [comment]
It's sad that the plugin could not work with local path - -!

**Comment by shamilovtim** [comment]
You can definitely serve local files with this plugin. Use the File API:
https://github.com/apache/cordova-plugin-file along with Platform API to make 2 separate platform calls. Log out your file paths and make sure you're hitting them accurately and normalizing the URLs.
