### ISSUE TITLE
Media Player Error: Unknown(1) - 2147483648

### ISSUE THREAD

**Issue by elenaaralla** [nchutchind/cordova-plugin-streaming-media#71]
**What version of Streaming-Meda-Cordova-Plugin are you using?**
1.0.2
**What version of Cordova are you using?**
6.3.0
**What devices are affected?**
Android 4.2.2
**Please describe the issue in detail, with relevant code samples**
simply calling the playVideo function, it returns the error in the subject:

> Media Player Error: Unknown(1) - 2147483648

this is my function

```
playVideo: function() {
        // Where are we playing the video from?
        var videoURL = cordova.file.applicationDirectory + "www/videos/VuforiaSizzleReel_2.mp4";
        alert(videoURL);
        // Play a video with callbacks
        var options = {
          successCallback: function() {
            alert("Video was closed without error.");
          },
          errorCallback: function(errMsg) {
            alert("Error playing video: " + errMsg);
          },
          orientation: 'landscape'
        };
        window.plugins.streamingMedia.playVideo(videoURL, options);
    }
```

this function is called after deviceready event

the alert displays this path: file:///android_asset/www/videos/myvideo.mp4

the video is in H.264 format with AAC audio.

using another plugin (com.dawsonloudon.videoplayer) I'm able to play video, so I think it's not a permission problem... 

**What did you expect to happen?**

the video start to play

**What actually happened?**

I got the error: Media Player Error: Unknown(1) - 2147483648

PS: I tried your plugin becouse it support IOS too.

Thank you, elena.

**Comment by elenaaralla** [comment]
It works if I use this URL: http://vevoplaylist-live.hls.adaptive.level3.net/vevo/ch1/appleman.m3u8
so, the question are:
1) with this plugin it's possible to play local file (local to www application foldet)?
2) what video format is spported?

**Comment by jalves** [comment]
Hi, i'm having exactly the same problem. Do you found a workaround?

**Comment by elenaaralla** [comment]
No,
sorry; it works only with file in streaming...not with local file;

the following plugin works with local file:
com.dawsonloudon.videoplayer 

but it supports Android devices only...

cheers, elena.

**Comment by ParVisual** [comment]
Hi, trying with this common youtube url, I get the same error. In other device I get the error ID 1004
https://www.youtube.com/watch?v=-ACXLb_0Cj0&t=138s
Any idea to fix it?
Thanks.

**Comment by anivaisu** [comment]
Hi ,

Here is my code


    let options: StreamingVideoOptions = {
      successCallback: () => { console.log('Video played') },
      errorCallback: (e) => { 
      console.log('Error streaming')
      console.log(e) 
     },
      orientation: 'landscape'
    };

    this.streamingMedia.playVideo('http://came3.nkansai.ne.jp:81/nphMotionJpeg?Resolution=640x480&Quality=Motion', options);

I am also getting this err.

Kindly advice me,

Thanks

**Comment by shwes002** [comment]
To fix this issue, follow the below mentioned steps:
-> add the below code in config.xml: 
	<allow-intent href="*" />
        <access origin="*" />
        <allow-navigation href="http://*/*" />
        <allow-navigation href="https://*/*" />
        <allow-navigation href="*" />
        <allow-navigation href="data:*" />
-> add the below code in index.html:
	<meta http-equiv="Content-Security-Policy" content="style-src 'self' 'unsafe-inline'; media-src *; connect-src *">

**Comment by shwes002** [comment]
To fix the issue, follow the below mentioned steps:
-> add the below code in config.xml: 

	    <allow-intent href="*" />
            <access origin="*" />
            <allow-navigation href="http://*/*" />
            <allow-navigation href="https://*/*" />
            <allow-navigation href="*" />
            <allow-navigation href="data:*" />
-> add the below code in index.html:

	    <meta http-equiv="Content-Security-Policy" content="style-src 'self' 'unsafe-inline'; media-src *; connect-src *">

**Comment by snowbreeze** [comment]
This doesnt solve it either. Weird case with me is that it plays the file at times and at times keeps loading and then times out

**Comment by nipungarg6138** [comment]
Does anyone solved the issue? I am still facing the issue. Tried above suggestions but its not working.

**Comment by nipungarg6138** [comment]
well i am also facing same issue. I tried everything suggested above but it is still not working. Anyone found any solutions?

**Comment by shamilovtim** [comment]
this plugin does support local files. you need to use the cordova file api to get a path to your local video file. that's your best bet. 

as far as the error i'm not sure what it is. try viewing the native debug logs.

**Comment by chandankumarshanbhag** [comment]
Finally i found the issue
According to Network security configuration (https://developer.android.com/training/articles/security-config#CleartextTrafficPermitted)
in the latest android devices cleartext support is disabled by default. so the player cannot reach out to any video on the internet
to solve this issue use this stackoverflow answer
https://stackoverflow.com/questions/54752716/why-am-i-seeing-neterr-cleartext-not-permitted-errors-after-upgrading-to-cordo

it works 100%
