### ISSUE TITLE
Playing out of fullscreen

### ISSUE THREAD

**Issue by acetechnology** [nchutchind/cordova-plugin-streaming-media#74]
This plugin is awesome but can the player not be triggered on full screen alone as many of us will like to give our users the options to go fullscreen or not. an instance is to be able to put a livechat below the player so while a stream is on, our users can interact. please is there a solution for that?

**Comment by azn1viet** [comment]
This should create a player control in a div where you can do more stuffs with the app, not just listen to music/video.

**Comment by GuilhermeSanches** [comment]
Does anyone have a workaround for this feat?

**Comment by noman115pk** [comment]
@acetechnology @GuilhermeSanches There was a modified version of this plugin just to handle this feature. It was available on Github but account does not exist anymore. link to [npm](https://www.npmjs.com/package/cordova-plugin-streaming-media-mod)

**Comment by acetechnology** [comment]
yeah, i did it. lol

**Comment by shamilovtim** [comment]
it's ultimately unnecessary. if you want inline video you can use html5 or the handful of other video plugins.
