### ISSUE TITLE
Loads doesn't play and then closes

### ISSUE THREAD

**Issue by yandev** [nchutchind/cordova-plugin-streaming-media#78]
**version 0.1.4**

**5.4.1**

**andriod**

`**document.getElementById("playvid").addEventListener("click", onplayvid)  
    };
    function onplayvid() 
    {  
        var videoUrl = "https://vimeo.com/186313893";  
        var options = {
            successCallback: function() {
                console.log("Video was closed without error.");
            },
            errorCallback: function(errMsg) {
                console.log("Error! " + errMsg);
            },
            orientation: 'landscape',
            shouldSplitVertically: true,
            shouldAutoClose: false,
        contentUrl: 'https://www.google.com'
    };
        window.plugins.streamingMedia.playVideo(videoUrl, options);
}

**`

*_for the video to start streaming from vimeo *_

*_the videoplayer interface comes up the loads but does not play then closes_

**Comment by v-ken** [comment]
@shamilovtim Any update on this? I'm getting the same behaviour on Samsung Galaxy S9.

**Comment by shamilovtim** [comment]
`var videoUrl = "https://vimeo.com/186313893";` isn't a video URL. link directly to an mp4 or mpeg file. i do think there should be better error handling that tells you why the error occurs though

**Comment by v-ken** [comment]
@shamilovtim Thanks for you quick response. This isn't the case for me though. It's really strange as the same video url works in my emulator and on a Galaxy S5, but not on a Galaxy S9. I'm trying to debug it now but if you have any ideas, please share =)

**Comment by shamilovtim** [comment]
open Android Studio and attach to process of the device, read the console log and see what the native error is

**Comment by v-ken** [comment]
@shamilovtim Thanks again for your help.

Ok, so I managed to reproduce the issue in the emulator running on API 23 (previously working fine on API 26). 

Following your suggestion, I attached Android Studio debugger and found this error being logged:
```W/MediaPlayer: Couldn't open file on client side; trying server side: java.io.FileNotFoundException: No content provider: https://caringlife.s3.ap-southeast-2.amazonaws.com/76e990bc136b80f29220f740a21e79c315360354811510560060.mp4```

Note that the video stream works if you copy and paste that in a browser. Also works on some emulators, so not sure what's causing it to fail on API 23.

The error message returned by this Cordova plugin is: `MediaPlayer Error: Unknown (1) -2147483648`

I've tested with other videos as well and it seems to work fine, so it's not related to a URL whitelist issue.

**Comment by v-ken** [comment]
Not sure if it's related to this: https://stackoverflow.com/questions/42106294/android-media-stream-error-java-io-filenotfoundexception-no-content-provider/42160256

**Comment by v-ken** [comment]
Update:

I tested the [video url](https://caringlife.s3.ap-southeast-2.amazonaws.com/76e990bc136b80f29220f740a21e79c315360354811510560060.mp4) in the internet browser on the Android emulator (API 23) and it doesn't work as well!

But, it works on iOS, my current laptop and Android API 26... 

I'm stumped.

**Comment by shamilovtim** [comment]
Find an mp4 file publicly available on the internet. Does it play? My suspicion is that your file path is simply wrong
