### ISSUE TITLE
IOS not playing video

### ISSUE THREAD

**Issue by chugas** [nchutchind/cordova-plugin-streaming-media#79]
**What version of Streaming-Meda-Cordova-Plugin are you using?**
com.hutchind.cordova.plugins.streamingmedia 0.1.4 "StreamingMedia"

**What version of Cordova are you using?**
6.3.1

**What devices are affected?**
Iphone 5
Version IOS 10.0.2

**Please describe the issue in detail, with relevant code samples**
When I play the video with a local video absolute path I only get a black screen with media controls (volume, play, next, previous) in IOS, Android is working ok. 

In Xcode I can see a Warning:
WARNING: ['StreamingMedia'] took '87.544189' ms. Plugin should use a background thread.

![img_0002](https://cloud.githubusercontent.com/assets/2066478/19531251/5d055ce2-960d-11e6-9abc-000a45305eab.PNG)

**Comment by gitlovenotwar** [comment]
I having the same issue... In android, local files works just fine but on a remote server, it's not playing. For ios, local files won't work the same you're showing right now, but on a remote server, it works fine.

Summary:
IOS 
 local - not working
server - working

Android
 local - working
 server - not working

**Comment by actusmedia** [comment]
any updates on this?

**Comment by noman115pk** [comment]
@chugas @jordanlance I used [cordova file plugin](https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-file/) and accesses the directory with `cordova.file.applicationDirectory+"www/videos/" + videoUrl` and i was able to play video locally on IOS.

**Comment by shamilovtim** [comment]
use the file plugin api.

additionally try removing and re-adding a platform. you can also try to remove node modules and do an npm install.
