### ISSUE TITLE
Not Playing Video - Ionic Android

### ISSUE THREAD

**Issue by RhuanGonzaga** [nchutchind/cordova-plugin-streaming-media#80]
Streaming-Meda-Cordova-Plugin: 0.1.4
Cordova Version: 6.4.0
Ionic Version: 2.1.4

Testing on my physical device running android 5.1.1 with this code:

`<button class="button button-block button-energized" ng-click="abrir()">Play</button>`

```
            $scope.abrir = function() {

              var options = {
                successCallback: function() {
                  console.log("Video was closed without error.");
                },
                errorCallback: function(errMsg) {
                  console.log("Error! " + errMsg);
                },
                orientation: 'landscape'
              };
              window.plugins.streamingMedia.playVideo("http://techslides.com/demos/sample-videos/small.mp4", options);

            };
```

There is any console errors.

**Comment by agoncharovdev** [comment]
Same problem with Ionic 2:
```
let options: StreamingVideoOptions = {
      successCallback: () => { console.log('Video played') },
      errorCallback: (e) => { console.log('Error streaming') },
      orientation: 'landscape'
    };
StreamingMedia.playVideo('https://www.youtube.com/watch?v=kqh9bKs9shE', options);
```

**Comment by pawanraocse** [comment]
Having same issue - Anyone find any solution for this ??

**Comment by darshantejani007** [comment]
Having same issue in ionic 2! seems this project isn't supported anymore

**Comment by gitlovenotwar** [comment]
It's not just on ionic 2. Any mobile it stops working, means it's the plugin itself that has problem. Any help to fixing it to play on android? Thanks.

**Comment by bcolflesh** [comment]
You guys sure it's the plugin and not your Content-Security-Policy meta attributes? They changed what's needed in the content attribute in recent Android versions. It's all working fine for me with the correct policy.

**Comment by khalisafkari** [comment]
Get visit
https://github.com/khalisafkari/Ionic-dash-palyer

**Comment by ParVisual** [comment]
Hi [bcolflesh](https://github.com/bcolflesh) can you tell us exatcly what you do with the Content-security-Policy? I working around this issue but I can't figure out how to fix it. Thanks!

**Comment by ParVisual** [comment]
Works now in my ionic app!
Installing the cordova-streaming-plugin, then  the [cordova-whitelist-plugin](https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-whitelist/) and then adding in the index.html:

`<meta http-equiv="Content-Security-Policy" content="style-src 'self' 'unsafe-inline'; media-src *; connect-src *">`

and in the config.xml:
```

<allow-intent href="*" />
<access origin="*" />
<allow-navigation href="http://*/*" />
<allow-navigation href="https://*/*" />
<allow-navigation href="*" />
<allow-navigation href="data:*" />


```
and in app.js, after device ready:

```
var videoUrl = "https://___MY_STREAMING_ENPOINT_HERE__.m3u8";

var options = {
		successCallback: function() {
		  alert("Video was closed without error.");
		},
		errorCallback: function(errMsg) {
		  alert("Error! " + errMsg);
		},
		orientation: 'landscape'
		};
window.plugins.streamingMedia.playVideo(videoUrl, options);
```

In my case only works well using .m3u8 access. AND only in real devices. 

Hope it helps.

**Comment by fdambrosio** [comment]
Hi, I'm not able to play HLS (m3u8) audio or video streaming. I've tried @ParVisual  workaround but it doesn't work for me.

**Comment by zhujunwei** [comment]
hey,i got a problem that the plugin works well on ios,but it plays as a black backgroung on android;

**Comment by giacomo1203** [comment]
Anyone find any solution?

**Comment by shamilovtim** [comment]
check your debug notes, this probably isn't related to the plugin.

**Comment by pptyasar** [comment]
@agoncharovdev  any solution for playing youtube video.

**Comment by shamilovtim** [comment]
it is strange to blame Ionic for YouTube's policy of not wanting you to stream their videos outside of their own embedded player

if you want to stream YouTube you need to use a YouTube embed
