### ISSUE TITLE
How could I add a Close-Button or Fullscreen-Button?

### ISSUE THREAD

**Issue by desmeit** [nchutchind/cordova-plugin-streaming-media#81]
Hi,

thanks for this plugin. I like to add a close- oder fullscreen-Button to the Player. I think it is more clearly for our users. How could I do this?

**Comment by SweetMei25** [comment]
This problem is still existing?
I would like add close button...
Please kindly give me a help or at least let me know the result.
Thanks

**Comment by shamilovtim** [comment]
Hi, this is a full screen native video player. The controls come from android VideoPlayer and iOS AVPlayer. I'm not sure why you would want to add buttons to native players but it doesn't seem practical or possible to me.

**Comment by ipehimanshu** [comment]
is there any way to give close button for that while playing video player,
reason is say user want to back to app from player then is there any way ?

Thank you
