### ISSUE TITLE
stops playing in android when screen gets locked

### ISSUE THREAD

**Issue by mohamedzaher88** [nchutchind/cordova-plugin-streaming-media#82]
stops playing in android when screen gets locked

**Comment by yascasa** [comment]
i have the same problem 
audio streaming have no sens if is stoping after locked screen or application on sleep

**Comment by alexhackney** [comment]
Have you tried using the background mode plugin?
[https://ionicframework.com/docs/native/background-mode/](https://ionicframework.com/docs/native/background-mode/)

**Comment by christianwico** [comment]
@alexhackney It doesn't work even with the `background-mode` plugin. Still stops when you press `HOME`, switch applications, and/or you put the device on *standby*.

```typescript
import { StreamingMedia, StreamingAudioOptions } from '@ionic-native/streaming-media';
import { BackgroundMode } from '@ionic-native/background-mode';

[...]

let options: StreamingAudioOptions = {
   bgColor: '#008A99',
   bgImage: image,
   successCallback: () => { this.background.disable(); }
};
    
this.background.enable();
this.streamingMedia.playAudio(
  `${ EnvironmentProvider.PODCAST_AUDIO_ENDPOINT }${ id }/audio`,
  options
);
```

**Comment by alexhackney** [comment]
Works here.

**Comment by christianwico** [comment]
@alexhackney Welp. Really doesn't work. I resorted to using HTML5 `<audio>` tags instead. Not the most *"native"* way to do it, but at least it works.

**Comment by oghanbari** [comment]
i have the same problem , playVideo is ok but playAudio has this problem and playback stopped on screen lock

**Comment by shamilovtim** [comment]
I can probably provide a PR in the future if necessary
