### ISSUE TITLE
Feature request - playback to wkWebView -> webGL texture instead of player

### ISSUE THREAD

**Issue by perqa** [nchutchind/cordova-plugin-streaming-media#84]
I wonder if it is possible to use the Cordova Streaming Media plugin without displaying the video player, but instead direct the video output to a webview texture, like this:

**[Native HLS playback] > Bridge API > wkWebView > WebGL context** 

Is that possible? I am currently experiencing massive problems with playing back HLS onto a texture using HTML5 video tag in WebView on iOS.

**Comment by shamilovtim** [comment]
I'd imagine it's possible but you'd have to provide the PR
