### ISSUE TITLE
Custom buttons for Android TV

### ISSUE THREAD

**Issue by FGMGIT** [nchutchind/cordova-plugin-streaming-media#85]
**There is any way to change the media player button color when it is focused?**

I'm working in a version for Android TV platform. The icons are working properly with remote control keys but they are not highlighted when focused. I would like also to control the amount of seconds of the back and forward buttons.

Any help or orientation will be helpful.

Thank you.
FGM

**Comment by naguchennai** [comment]
not available to go android studio and xcode.. happy coding

**Comment by shamilovtim** [comment]
@FGMGIT have newer versions of android tv fixed this?
