### ISSUE TITLE
App crashes on transparent background

### ISSUE THREAD

**Issue by FabiGjuzi** [nchutchind/cordova-plugin-streaming-media#91]
If I set bgColor to transparent the application crashes.
Is there any way to not play audio on a black fullscreen window?
Thanks in advance!

**Comment by alexhackney** [comment]
You could use a bg image to show album art?

**Comment by jairemix** [comment]
```
plugins.streamingMedia.playAudio('audio.mp3', {
	initFullscreen: false
})
```

**Comment by acefxlabs** [comment]
@jairemix 
Init Fullscreen did not work

**Comment by shamilovtim** [comment]
This is a confusing question. Why not use #FFFFFF for white? You don't need `transparent` for a white window.
