### ISSUE TITLE
ios  not play aduio

### ISSUE THREAD

**Issue by shenmingxuanyi** [nchutchind/cordova-plugin-streaming-media#92]
the ios not play aduio ，or can play audio ,bug can't close,

**Comment by mmirzaee** [comment]
same issue ! any solution ?

**Comment by cocowalla** [comment]
It plays MP3 for me, but not AAC-encoded MP4 files

**Comment by CarlosAyala** [comment]
You need to convert the video to a codec that IOS have in native form.

**Comment by cocowalla** [comment]
@CarlosAyala iOS is meant to be able to play AAC https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/StreamingMediaGuide/FrequentlyAskedQuestions/FrequentlyAskedQuestions.html

**Comment by CarlosAyala** [comment]
"HE-AAC or AAC-LC up to 48 kHz, stereo audio"

**Comment by cocowalla** [comment]
It's been a while, but I recall verifying at the time that the video did indeed match the specs stated by Apple

**Comment by shamilovtim** [comment]
the latest PRs have iOS playing AAC but not mp3. but you need to grab all of my PRs.

**Comment by shamilovtim** [comment]
please check the latest PRs and confirm this is still happening
