### ISSUE TITLE
Failed to fetch plugin

### ISSUE THREAD

**Issue by owen-mills** [nchutchind/cordova-plugin-streaming-media#98]
**What version of Streaming-Meda-Cordova-Plugin are you using?**

**What version of Cordova are you using?**
7.0.1
**What devices are affected?**

**Please describe the issue in detail, with relevant code samples**
I input `cordova plugin add cordova-plugin-streaming-media` into the cmd
**What did you expect to happen?**
I expected the plugin to install
**What actually happened?**
I got this error:
```
Error: Failed to fetch plugin file:node_modules/cordova-plugin-streaming-media via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: cmd: Command failed with exit code 1 Error output:
npm ERR! code ENOLOCAL
npm ERR! Could not install from "node_modules\cordova-plugin-streaming-media" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\admin\AppData\Roaming\npm-cache\_logs\2017-09-12T20_29_50_840Z-debug.log
```

**Comment by proustibat** [comment]
I had the same problem. Switching the node version from 8 to 7 solved the issue (I used nvm for example). It happens with other packages.
